### ISSUE TITLE
Missing fields check does not work for "Select hours" field

### ISSUE THREAD

**Issue by kunal-mohta** [sarthak-sehgal/timetable-visualizer#1]
Probably because `hours` is an empty `Array`, which is not being counted as `null/undefined` [here](https://github.com/sarthak-sehgal/timetable-visualizer/blob/master/main.js#L85)

**Comment by sarthak-sehgal** [comment]
Fixed ❤️

**Comment by kunal-mohta** [comment]
Noice :1st_place_medal:
